ALTER TABLE EMPLOYEE ADD COLUMN email VARCHAR(255);
ALTER TABLE EMPLOYEE ADD COLUMN phone VARCHAR(255);
ALTER TABLE EMPLOYEE ADD COLUMN bic VARCHAR(255);
ALTER TABLE EMPLOYEE ADD COLUMN iban VARCHAR(255);
ALTER TABLE EMPLOYEE ADD COLUMN BANK_NAME VARCHAR(255);

Update EMPLOYEE set email = 'Missing Email' where EMPLOYEE.email IS NULL;
Update EMPLOYEE set phone = 'Missing phone' where EMPLOYEE.phone IS NULL;
Update EMPLOYEE set bic = 'Missing bic' where EMPLOYEE.bic IS NULL;
Update EMPLOYEE set iban = 'Missing iban' where EMPLOYEE.iban IS NULL;
Update EMPLOYEE set BANK_NAME = 'Missing bankName' where EMPLOYEE.BANK_NAME IS NULL;


ALTER TABLE EMPLOYEE ALTER COLUMN  email SET NOT NULL;
ALTER TABLE EMPLOYEE ALTER COLUMN  phone SET NOT NULL;
ALTER TABLE EMPLOYEE ALTER COLUMN  bic SET NOT NULL;
ALTER TABLE EMPLOYEE ALTER COLUMN  iban SET NOT NULL;
ALTER TABLE EMPLOYEE ALTER COLUMN  BANK_NAME SET NOT NULL;


ALTER TABLE COMPANY DROP COLUMN  bank_name;
ALTER TABLE COMPANY DROP COLUMN  IBAN;
ALTER TABLE COMPANY DROP COLUMN  BIC;


